# Generated by Django 3.2.9 on 2022-05-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220525_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
