# Generated by Django 3.2.9 on 2022-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='rank',
            field=models.IntegerField(choices=[(5, 'Five points'), (4, 'Four points'), (3, 'Three points'), (2, 'Two points'), (1, 'One point')]),
        ),
    ]
